### ISSUE TITLE
summer and winter annuals

### ISSUE THREAD

**Issue by emchristensen** [weecology/PortalData#105]
In Portal_plant_species.csv, is there a difference between "Summer and Winter Annuals" and "Winter and Summer Annuals" in the community column? @gmyenni

**Comment by gmyenni** [comment]
Well, yeah, there is. But that column's probably more useable with fewer categories. You can just change it all to `Winter and Summer Annuals`. That'll still work to indicate species that could be found in either community, for whatever life history reason.

**Comment by emchristensen** [comment]
If there's a legit reason to distinguish between those two maybe we should leave them as is -- but we should definitely put a note about it in the metadata.  Now that I'm working with the plant data those little details are bothering me.  
Here's another detail I'm sure nobody cares about but me: in Portal_plant_species.csv when the family is unknown it's called "Unknowns" but if there's an unknown in any other column it's "Unknown."  Any objections to me changing that so they're all just "Unknown"?  It would just make me happy to have a single value to indicate unknown information -- makes it easier when I'm trying to filter out rows with "unknown" in any column.

**Comment by gmyenni** [comment]
Since you're actually using it, you would know what works and what doesn't. 

The community column is there so people can appropriately separate species when they do yearly sums or whatever, without having to know too much about the plants. They just need to know that something in the `Winter and Summer Annuals` group could actually be interacting with either the `Winter Annuals` or `Summer Annuals`. It's up to them how they're actually going to deal with that. But I think the values `Winter Annuals`, `Summer Annuals`, `Winter and Summer Annuals`, `Perennials` and 'Unknowns' are enough to help people separate them appropriately. I think you're right that if there are too many values in that column, it starts to be unusable. There are life history differences within the `Winter and Summer Annuals` in the reason why they might be in both communities. I had them separated before into the species that germinate in the spring and flower in the summer, and everything else. But maybe that's a level of detail that the user should actual have to be familiar with to use. We could just put those details in the metadata, so people know that there may be more to consider when deciding what species are interacting, and that the `Community` column is just a rough cut.

That's really weird about `Unknowns` in `Family`. At first I thought you were talking about `Community`, that used to be plural. So definitely change that back. It was `Unknowns` in the `Community` column because the values in that column are plural. ie A species is in the `Unknowns` group, it's not `Unknown` like the species name or family name. eg A user could choose to sort by `Family`, where `unkn gras` would stay with the `Poaceae` and something like `aste sp` would stay with`Asteraceae`, or they could choose to sort by `Community`, where those species would stay with the other `Unknowns` and be removed or whatever. But I'd actually change the other values so they're all singular (`Summer Annual`), if that seems better.

Change stuff however you see fit. Once you're done, you can just tell me what you did and why, and I'll add a better description to the metadata with all these details about how to use these columns.

**Comment by emchristensen** [comment]
Ok.  I might change a few things.  What started me down this path was wanting to get a list of plant names excluding anything that wasn't completely identified, so filtering out "unkn forb" as well as "dale sp" type things.  Right now I can accomplish this by filtering by two columns (commonname != "Unknown" && species != "sp.").  I have to do this because some have like partial commonnames: zinn sp has commonname Unknown zinnia.  That might be an easy way to solve this since I'm sure nobody cares about the difference between "unknown" and "unknown zinnia" -- anything that isn't completely identified gets commonname="Unknown". (Assuming everything that is completely identified has some sort of commonname)
Looking at the zinnias brings up one more thing: there are two rows for each zinnia, with one designated a subshrub and one a perennial.  Is that because they belong to both categories?  That might be worth putting in the metadata too, in case someone was expecting the "speciescode" column to be a unique identifier (like I was)
I like the idea about un-pluralizing the community designations, I'll do that too.

**Comment by gmyenni** [comment]
Species code is definitely supposed to be a unique identifier. Things that belong to more than one community are handled in our field species lists. I guess some duplicates remain from creating those lists, but they should be deleted. Let's just get rid of `Subshrub` and call all those `Perennial`. And delete any duplicates.

You could use `commonname` to indicate unknowns, or you could add a new column, `unidentified` or something, with just 1s and 0s.

**Comment by emchristensen** [comment]
I used commonname to indicate unknowns, rather than add a new column.  And speciescode should be a unique identifier now

**Comment by gmyenni** [comment]
Has this all been implemented in the repo?

**Comment by emchristensen** [comment]
Yep, in a series of commits I made on Aug 23

**Comment by gmyenni** [comment]
Yay! So we can close this?

**Comment by emchristensen** [comment]
yes.
