### ISSUE TITLE
Consolidation of metadata in Readme files?

### ISSUE THREAD

**Issue by ha0ye** [weecology/PortalData#136]
I had been looking at the "Readme.md" in the "Rodents" folder for info on the plot treatments, and it points to the CSV files for the treatments.

However, the "Readme.md" in the "SiteandMethods" folder seems to contain a bit more info about the different treatments.

There's also a bit of redundancy in the general site descriptions in the Readme files across the subfolders.

It might be cleaner to keep the Readme in the SiteandMethods folder as a full description of the methods, and modify the subfolder Readmes to instead be a simple description of the files in that subfolder?

**Comment by gmyenni** [comment]
The current READMEs are just the metadata copied and pasted from the EcolArch data paper (well, with a little bit of improvement). Which is why they're so redundant. So yeah, we can totally change the way that all is organized.
What if I just put a consolidated methods in the README in the main folder? That isn't currently being used for anything and`SiteandMethods` has files that could use describing as well.

**Comment by ha0ye** [comment]
My personal preference is for top-level READMEs to be sparse, but that is just me.

An alternative to having all the metadata in a README is to make some sort of metadata.md or methods.md file that is referred to from the README.
