### ISSUE TITLE
Build still passes with failed tests

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#141]
How do we force the build to fail when a test fails?

**Comment by ethanwhite** [comment]
That should happen automatically. Is this happening for every failure or just in some cases. If you can give me some details and point me at an example I'll take a look.

**Comment by gmyenni** [comment]
The pull request that Erica just merged is an example. It passed even though a test failed. Now that it's merged there's an error in the build. I think that (unrelated) error also happened in the PR, and also didn't cause it to fail or error.

**Comment by gmyenni** [comment]
That's this PR #140, in case that's confusing.

**Comment by gmyenni** [comment]
Reopening this because it seems that the build will fail if `testthat.R` errors, but **not** if a test fails. 
It appeared to be working before because there was an error as a result of `testthat.R` being in the wrong place. But now that that's fixed, the build doesn't fail when there are only failed tests.
Example: https://travis-ci.org/weecology/PortalData/builds/292255248

**Comment by gmyenni** [comment]
Also, can't get tests to work with the correct folder structure (tests/testthat.R and tests/testthat/test-...).

**Comment by gmyenni** [comment]
`test_dir` doesn't force errors like `test_package` does, and `stop_on_failure = TRUE` doesn't appear to do anything.

**Comment by ethanwhite** [comment]
I think I've fixed the core issue in #163.

With regards to tests not working in the standard folder structure it looks like this is due to the fact that the test code calls at least one function, `update_moon_dates`, that uses relative paths to look up data. Since the tests are running from the tests directory this path is wrong. Since this code is also getting called by `writenewmoons` which is currently being called separately by the CI we can't just trivially add another `../` to the paths. I think it's fine the way it is, but we can also untangle the paths if desired to move the tests. My suggestion for now is that we just leave the location of the files where they are and close this after #163 is in.

**Comment by gmyenni** [comment]
Woohoo!
