### ISSUE TITLE
plant quadrat column name

### ISSUE THREAD

**Issue by emchristensen** [weecology/PortalData#143]
should we change 'quadrat' to 'stake' in the Portal_plant_quadrats.csv? There was some confusion last time we mass-entered data because the column name on the physical data sheet is 'stake'.  Changing this would also bring the plant data in line with the rodent and ant data, both of which have 'stake' columns.

**Comment by gmyenni** [comment]
Quadrat indicates that it's the plant stake location, not the rodent stake. In the ants and rodent data it's called stake because they use the rodent stake location. I think it's good to keep them different. eg It forces so.eone to correctly link the coordinates data to both stake and quadrat.

If it's confusing, we should change the data sheets.

**Comment by emchristensen** [comment]
oh, I thought since they were numbered according to the rodent stake they're closest to it was kind of the same thing, but if someone is using actual GPS coords yeah they should remain separate.  I'll change the data sheet.
