### ISSUE TITLE
Archive.R failing in branches again

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#301]
error in checkout_branch(branch, force) : 
  Error in 'git2r_checkout_tree': 2 conflicts prevent checkout
Calls: <Anonymous> -> checkout_branch

**Comment by gmyenni** [comment]
Sorry, I should have said, failing in PRs. Seems to work fine in master.

**Comment by ha0ye** [comment]
Ok, this, and the issues that @juniperlsimonis encountered recently, led me down a lot of tunnels about git checkout conflicts and such.

Suffice to say that I think we should modify `archive.R` so that it does better logic-handling depending on the workflow:

* when should archive.R make a new commit in the travis CI runtime environment?
  - probably only if it's a cron check or some other commit on `master` branch
* if so, the code on lines 42:56 can probably be folded into the if clause on line 67

I'll set up a PR for this change.
