### ISSUE TITLE
Too many Slack notifications!

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#349]
Ideally we *only* want to be notified in Slack (portal-logistics) when master builds are failing. Not PR-master. No other branches. And no notifications when builds pass.

`on_success: never` does not work (notifications still get sent).
`if: branch = master` breaks the entire Travis config.

**Comment by gmyenni** [comment]
I've tried changing the config to notify only when build status changes. Still doesn't work.
I don't want to spam the slack channel, I just want notifications when I need to go fix something. esp. big problem right now, given #385

**Comment by ethanwhite** [comment]
Just to clarify. Is the ideal behavior to report every failure on `master` or just the first failure in a string? If it's every failure then I can update #386, but if due to #385 we only want the first then I can leave `on_failure` as `change`. My initial reaction is that if we're repeatedly failing we want to hear about it (so that we can restart build etc.), but I'm happy to due whatever the folks monitoring `portal-logistics` think is best.

**Comment by gmyenni** [comment]
Yeah, you can change it to always. At least, once it's working we can always adjust it later if we don't like it.

**Comment by gmyenni** [comment]
Appears to be working, as of https://github.com/weecology/PortalData/commit/cdb5b190cfe4a5f1a3cbd6622bb11fd4bab6c904 (our first build to pass in awhile).
