### ISSUE TITLE
How to organize weather files?

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#59]
I've started adding the remotely-accessed weather data from the new station (https://github.com/weecology/PortalData/pull/58). The data is still hourly, like the old station, so we could keep building the original `Portal_weather.csv` file and just have `NA` values in the new columns until November of 2016. I assume this would be preferable, like @ethanwhite suggested for the plant files. But, we have significant overlap in which the two stations are both collecting data (November 2016 until we take down the old station). So I imagine the options are:

1. Just pick one or the other (the unused data will still be available in the Dropbox folder)

2. Use the mean

3. Include both and a note in the metadata to either do option 1 or 2 above yourself

4. Keep them as separate files and names the old station `Portal_weather19892017.csv` like I did in https://github.com/weecology/PortalData/pull/58

**Comment by ethanwhite** [comment]
Yeah, this is a tough one because you want to have all of the data, make it easy to use, and also not make it easy for users to make mistakes.

My suggestion here would be to choose either (1) or (2) for the main file, whichever we think is the most accurate representation of the newer data. This makes things simple for users. We then need to deal with maintaining all of the raw data. I'd suggest adding an additional table called something like `Portal_weather_station_overlap.csv`. This can then hold the overlapping records anytime the weather station is changed with a column indicating the weather station number. That way someone can also go back and analyzing these overlapping regions if they want to and all of the raw data is available.

Does that make sense to other folks? @skmorgane @bleds22e @emchristensen

**Comment by emchristensen** [comment]
I agree that one main weather file would be the way to go.  I think I would vote for (1) personally and just use the new weather station data, since the new instruments have actually been calibrated recently and so should theoretically be getting better measurements.  I like the idea of keeping the raw data in a separate file (am I crazy or was there also some overlap between the 1989 and 2002 stations?)

**Comment by gmyenni** [comment]
@emchristensen and @ethanwhite I like it. I agree, the new station data is probably more accurate. The history of the weather stations (what we know, at least) is in the [Site Log](https://github.com/weecology/lab-wiki/wiki/Portal-Site-Log). It sounds like the 1989 station was fully on the fritz by the time is was replaced in December of 2002, so that's why there isn't any overlapping data (at least none I could find in the Dropbox). There was overlap between the 1980 data collection and the 1989 station, but that isn't a problem because one was daily and one hourly, so we can't combine them anyway.

**Comment by gmyenni** [comment]
Okay how does this look? https://github.com/weecology/PortalData/pull/58
