### ISSUE TITLE
99 in stake column - rodent data

### ISSUE THREAD

**Issue by emchristensen** [weecology/PortalData#93]
remove 99 from stake column in rodent data -- we no longer use 99 to represent NA
also check to see if there are 99 or -99s anywhere else in the data

**Comment by bleds22e** [comment]
Did we ever make an official decision on removing the 99s and leaving them blank?

**Comment by gmyenni** [comment]
Yeah, all the 99s should be removed.

**Comment by emchristensen** [comment]
I'll happily work on this as a means to avoid all the other stuff I don't feel like doing

**Comment by emchristensen** [comment]
pull request submitted.  I only removed the 99s where note1=2 (plot trapped but empty).  There were a total of 5 lines where there was a 99 but some other note1 -- I left these in case they actually mean something (they were all non-census negative period codes anyway).  Side note -- do we have any info on what all these non-census negative period codes were for?  I know we did one when we did the plot switch in 2015 and when we trapped off-site in 2012, it might be beneficial to keep some notes on what they were all about for future generations (side experiments or whatever)

**Comment by bleds22e** [comment]
Oh, there were only 99s where there were note1 = 2 (or, mostly)? I kind of expected some of them to have note1 = 1 (missing data) or = 3 (suspect stake). Interesting. I'll go ahead and merge. 

A readme or something about the neg period codes would probs be a good idea.

**Comment by emchristensen** [comment]
yep, it seemed to be a thing to use stake 99 when the plot was empty.  maybe that practice predated the presence of a note1 column to explicitly note this?

**Comment by bleds22e** [comment]
Perhaps. 
I merged it even though it's failing a test because there is no reason this should be failing a test (poor logic). WHY, though?

**Comment by gmyenni** [comment]
It's just failing because the rodent tests need to be rewritten. Doesn't have anything to do with the PR. They'll all fail until those get fixed.

**Comment by gmyenni** [comment]
The 99s and -99s have been getting removed in waves. So I think all missing data, etc., ones have already been removed.

If the only remaining 99s are negative period codes, then the note1 column should indicate the proximate reason why (outside plots, no fences, all gates open, etc.). If we have a negative period that doesn't have a note to explain what's wrong with it, we can add a new note. And we should definitely add something to the README explaining that negative period codes should not be used for analyses, because they don't follow the protocol. That should be sufficient. 

I don't think we need more info as to the ultimate reason why the period is negative (ie what in the hell the person was thinking). I doubt we could even figure that out for a lot of them.

**Comment by emchristensen** [comment]
So you're saying I should get rid of those last 5 99s?  The note1s in those entries are unspecific: a mix of 5, 6, 8 (gates open, non-survey, gates open + non-survey) (they were clearly all empty plots as well, which brings us back to the note1 hierarchy question)

**Comment by gmyenni** [comment]
Yeah, there should be no 99s or -99s left in the data anywhere. They were used inconsistently between RAs, and with inconsistent meanings, so don't mean anything anyway.

Do you mean the note1 is `5,6,8`? Or some are `5`, some are `6` and some are `8`?

If it's the second one, that's fine. All that a data user needs to know is, the plot was trapped on this date, but don't include it in your analyses, because it was a non-survey trapping (something about the protocol disqualifies it). 

If the plot was empty, but it's a negative period code, the note1 that indicates why it's negative should take precedence over note `2`. That is, it should indicate that the plot was trapped on a certain date, but with something weird about the trapping (gates open or no fences or whatever). In that case it can just be inferred from the rest of the data being empty that nothing was caught.

**Comment by emchristensen** [comment]
They each just have one number in note1.  I'll leave them as is

**Comment by gmyenni** [comment]
Is that it for 99s then? :)

**Comment by emchristensen** [comment]
yep, closing this
